require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'ReactNativePortals' do
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!
  use_frameworks!
  use_react_native!(path: config['reactNativePath'])
  # Pods for ReactNativePortals
  pod 'IonicPortals', '~> 0.7.3'
  pod 'IonicLiveUpdates', '~> 0.4.0'
end
